#!/usr/bin/env python3
"""Generate catalogue artifacts from the harvested reference-mod knowledge.

Data lives inline (curated from code analysis with evidence in mods/*.md).
Outputs: catalog.json / catalog.csv / system-matrix.csv / pattern-candidates.jsonl
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "knowledge" / "reference-mods"

MODS = [
    dict(id="ref:guigu-cultivation", name="Guigu Cultivation", tier="A", conf="Mostly Verified",
         summary="完整修仙/武道体系：月结修炼、境界突破、功法绝技、轮回转世、宗门王国社会系统，含大量读档稳定性补丁",
         primary=["Actor", "Traits", "Combat", "Kingdom", "Save/Persistence"],
         secondary=["City", "Events", "UI", "World", "Mod Lifecycle", "Utility"],
         techniques=["Harmony Prefix", "Harmony Postfix", "Harmony Transpiler", "Reflection", "Asset registration", "Custom data", "Save/load", "Event subscription", "UI injection", "Localization"],
         harmony=True, ui=True, assets=True, persistence=True, evidence=7,
         wb=["Actor.data", "Actor.updateStats", "AssetManager", "Kingdom.setKing", "MapBox.on_world_loaded", "BatchActors", "SaveManager", "TabManager.CreateTab"],
         nml=["BasicMod<T>.OnModLoad (Verified)", "BasicMod<T>.GetConfig (Unverified)"],
         patterns=[("per-patch-isolated-patching", "逐补丁类隔离 ApplyPatch，单补丁失败不炸全 mod"),
                   ("actor-data-key-state-store", "actor.data 字符串键集中管理自定义状态"),
                   ("frame-sliced-world-simulation", "分帧切片月结 + 读档牺牲窗"),
                   ("save-slot-file-persistence", "存档槽目录文件持久化")]),
    dict(id="ref:powerbox", name="PowerBox", tier="A", conf="Verified",
         summary="NML Feature 体系实现 40+ 新神力（建筑升降级/指定国王/创建文化宗教氏族/特殊生物），Feature 自动发现的教学样本",
         primary=["Assets", "UI", "Mod Lifecycle"],
         secondary=["Kingdom", "City", "Culture", "Religion", "Actor", "Diplomacy", "Utility"],
         techniques=["NML Feature registration", "Asset registration", "UI injection", "Custom scheduler", "Reflection"],
         harmony=True, ui=True, assets=True, persistence=False, evidence=5,
         wb=["AssetManager.drops", "GodPower", "DropAsset", "Kingdom.setKing", "Actor.setProfession", "Finder.getUnitsFromChunk", "TabManager.CreateTab"],
         nml=["NeoModLoader.api.features.* (Verified)", "BasicMod<T> (Verified)", "ResourcesFinder (Unverified)"],
         patterns=[("nml-feature-per-power", "每个神力一个 ModAssetFeature 类"),
                   ("godpower-dropasset-pair", "GodPower+DropAsset 配对注册复用落点管线"),
                   ("custom-power-tab-sections", "自建 tab 二级分区切换"),
                   ("clone-derive-actor-asset", "actor_library.clone 派生生物")]),
    dict(id="ref:xavii-nation-types", name="Xavii Nation Types", tier="A", conf="Mostly Verified",
         summary="57 种国家类型系统（继承模式驱动王位/头衔/意见）+ Land Types 城市加成 + BetterWars 战争结局重做 + 国策法",
         primary=["Kingdom", "Diplomacy", "Traits", "Events"],
         secondary=["City", "Save/Persistence", "UI", "Culture", "Religion", "Combat", "World", "Mod Lifecycle"],
         techniques=["Harmony Prefix", "Harmony Postfix", "Custom asset", "Custom data", "UI injection", "Localization"],
         harmony=True, ui=True, assets=True, persistence=True, evidence=6,
         wb=["AssetManager.kingdoms_traits", "KingdomTrait", "WorldLogAsset", "kingdom.data.custom_data_string", "KingdomBehCheckKing.execute", "WarManager", "SuccessionTool.findNextHeir"],
         nml=["BasicMod<T> (Verified)", "ModObjectFeature<Harmony> (Verified)"],
         patterns=[("kingdom-trait-custom-data-hybrid", "定义表→KingdomTrait→custom_data_string 三层结构"),
                   ("worldlog-asset-text-replacer", "WorldLogAsset text_replacer 带参日志"),
                   ("behaviour-node-prefix-system-tick", "行为树节点 Prefix 作系统 tick 入口"),
                   ("definition-table-driven-content", "纯定义表驱动内容+本地化")]),
    dict(id="ref:xuanjian-xianzu", name="玄鉴仙族 (WuLin)", tier="A", conf="Mostly Verified",
         summary="修仙文明模拟：境界 trait/法宝物品/洞天建筑/权柄争夺，反编译代码，硬依赖 VideoCopilot",
         primary=["Actor", "Traits", "Buildings", "Combat", "Items", "UI", "Save/Persistence"],
         secondary=["World", "Events", "Utility", "Mod Lifecycle"],
         techniques=["Harmony Prefix", "Harmony Postfix", "Reflection", "Custom data", "Save/load", "Asset registration", "UI injection"],
         harmony=True, ui=True, assets=True, persistence=True, evidence=6,
         wb=["AssetManager.traits", "Actor.getHit", "MapBox.updateSimulation", "World.world.buildings.addBuilding", "ActorEquipmentSlot.setItem", "MapStats.custom_data"],
         nml=["BasicMod.OnModLoad (Verified)", "TabManager/PowerButtonCreator (Verified)"],
         patterns=[("safe-harmony-batch-apply", "容错式批量补丁（反射枚举+单失败跳过）"),
                   ("world-string-tsv-persistence", "TSV+Base64 世界持久化（seed 检测/重试/脏检查）"),
                   ("sim-tick-bus-postfix", "单 updateSimulation postfix 聚合系统 tick")]),
    dict(id="ref:actorhistory", name="ActorHistory", tier="A", conf="Verified",
         summary="收藏单位生平史书：钩 40+ 事件按 7 类叙事生成着色文本，写 SQLite+txt，NML 窗口 UI + 热键",
         primary=["Events", "Save/Persistence", "UI"],
         secondary=["Actor", "Kingdom", "City", "Clan", "Alliance", "War"],
         techniques=["Harmony Prefix", "Harmony Postfix", "Custom data", "Save/load", "UI injection", "Event subscription"],
         harmony=True, ui=True, assets=False, persistence=True, evidence=6,
         wb=["Actor.checkDeath", "Actor.newKillAction", "WarManager.endWar", "Kingdom.setKing", "UnitWindow.OnEnable", "MapBox.clearWorld", "actor.data"],
         nml=["BasicMod<T> (Verified)", "SingleAutoLayoutWindow.CreateWindow (Verified)", "PowerButtonCreator (Verified)"],
         patterns=[("favorite-actor-event-recorder", "钩事件→分类→SQLite 史书"),
                   ("sqlite-mod-storage", "sqlite-net 带世界键的嵌入式存储"),
                   ("clone-button-ui-injection", "克隆按钮注入任意窗口")]),
    dict(id="ref:xuanmen-daojie", name="玄门道界", tier="A", conf="Mostly Verified",
         summary="修仙模拟：11 境界/18 自定义属性/真伤克制战斗/灵炁经济/天劫轮回夺舍飞行/幽冥领域 terraform，约 1.6 万行",
         primary=["Actor", "Traits", "Combat", "Save/Persistence", "UI"],
         secondary=["World", "Map", "Events", "Assets", "Utility"],
         techniques=["Harmony Prefix", "Harmony Postfix", "Harmony Transpiler", "Custom data", "Asset registration", "UI injection", "Save/load"],
         harmony=True, ui=True, assets=True, persistence=True, evidence=6,
         wb=["Actor.getHit", "Actor.updateStats", "BatchActors", "BaseStats", "MapStats.custom_data", "MapAction.terraformMain", "UnitWindow"],
         nml=["BasicMod<T>.OnModLoad/GetConfig (Verified)", "TabManager.CreateTab (Verified)"],
         patterns=[("dual-track-stat-persistence", "Get 走 stats/Set 走 data 双轨持久化"),
                   ("custom-data-world-resource", "custom_data 世界资源+life_dna 指纹"),
                   ("batchactors-system-bus", "BatchActors.u8 postfix 每帧系统总线"),
                   ("transpiler-stat-injection", "updateStats Transpiler 注入属性"),
                   ("persistent-actor-archive", "persistentDataPath JSON 完整保存 Actor")]),
    dict(id="ref:thefantasyworld", name="TheFantasyWorld", tier="A", conf="Mostly Verified",
         summary="RPG 层：12 职业/修仙式升级突破（grade1-91）/天赋特质/战斗计算（护盾魔抗闪避）/神明复活",
         primary=["Actor", "Traits", "Combat", "Mod Lifecycle"],
         secondary=["UI", "Save/Persistence", "World", "Assets", "Events"],
         techniques=["Harmony Prefix", "Harmony Postfix", "Asset registration", "Custom data", "UI injection"],
         harmony=True, ui=True, assets=True, persistence=True, evidence=5,
         wb=["AssetManager.base_stats_library", "Actor.die", "BaseSimObject.changeHealth", "BabyMaker.makeBaby", "map_stats.custom_data"],
         nml=["BasicMod<T> (Verified)", "TabManager/PowerButtonCreator (Verified)"],
         patterns=[("custom-basestat-registration", "BaseStatAsset 自定义属性注册"),
                   ("trait-factory-with-action-delegate", "trait 工厂+action_special_effect 每帧 tick"),
                   ("death-protection-prefix-chain", "die Prefix 死亡保护链+ForceKill 队列绕过")]),
    dict(id="ref:shtoolkit", name="SHToolkit", tier="A", conf="Mostly Verified",
         summary="辅助工具集：自定义地图尺寸/超级暂停/随机刷兵 WorldBehaviour/自动存档间隔/UI 增强/本地化扩展/DLL 释放",
         primary=["Utility", "UI", "Save/Persistence", "Mod Lifecycle"],
         secondary=["World", "Actor", "Events", "Assets"],
         techniques=["Harmony Prefix", "Harmony Postfix", "Asset registration", "Save/load", "UI injection", "Reflection"],
         harmony=True, ui=True, assets=True, persistence=True, evidence=5,
         wb=["WorldBehaviourAsset", "AssetManager.world_behaviours", "AutoSaveManager", "MapBox.checkMainSimulationUpdate", "WorldTile.setTileType"],
         nml=["BasicMod.OnModLoad (Verified)", "[ModEntry] (Unverified-NCMS)"],
         patterns=[("worldbehaviour-runtime-scheduler", "运行时 WorldBehaviourAsset 闭包周期任务"),
                   ("dictionary-toggle-settings-center", "字典+回调设置中心"),
                   ("persistent-json-config", "persistentDataPath JSON 设置")]),
    dict(id="ref:chinesename", name="ChineseName", tier="A", conf="Verified",
         summary="中文词库+模板引擎替换全游戏命名，数据驱动+热重载，IPatch 程序集扫描自动注册的工程化范本",
         primary=["Utility", "Assets", "Mod Lifecycle"],
         secondary=["Save/Persistence", "Events", "Culture", "Religion", "City", "Kingdom"],
         techniques=["Harmony Prefix", "Harmony Transpiler", "Reflection", "Custom asset", "Localization", "Custom data"],
         harmony=True, ui=False, assets=True, persistence=True, evidence=5,
         wb=["Actor.getName", "ActionLibrary.turnIntoZombie", "City.generateName", "Kingdom.newCivKingdom", "WarManager.newWar", "Actor.data"],
         nml=["BasicMod/IReloadable (Verified)", "Hotfixable attribute (Verified)"],
         patterns=[("assembly-scan-auto-patch-registration", "IPatch 接口+程序集反射扫描自动注册"),
                   ("dual-asset-registration-compat", "双注册兼容防 vanilla NRE"),
                   ("transpiler-literal-replace", "Transpiler 字符串字面量替换"),
                   ("non-destructive-prefix-fill-and-pass", "Prefix 填充后放行的非破坏式 hook")]),
    dict(id="ref:sandbox", name="Sandbox", tier="B", conf="Verified",
         summary="上帝沙盒操控：强制归属/封王/画线定居/建筑放置/基因编辑/特质禁用器；含泛型类 manual patch 配方",
         primary=["Actor", "City", "Kingdom", "UI"],
         secondary=["Traits", "World", "Assets", "Buildings", "Mod Lifecycle"],
         techniques=["Harmony Prefix", "Harmony Postfix", "Asset registration", "UI injection", "Reflection"],
         harmony=True, ui=True, assets=True, persistence=False, evidence=6,
         wb=["AssetManager.powers.clone", "GodPower", "MetaObjectWithTraits.addTrait", "kingdom.setKing", "WindowPreloader", "ScrollWindow"],
         nml=["BasicMod.OnModLoad (Verified)", "Config.preload_windows (Verified)", "TabManager (Verified)"],
         patterns=[("generic-type-manual-harmony-patch", "MakeGenericType+CreateProcessor 泛型 patch"),
                   ("powers-clone-drop-power-template", "powers.clone+DropAsset 落地触发神力"),
                   ("button-builder-fluent-ui", "Builder 模式纯代码按钮")]),
    dict(id="ref:optime", name="Optime", tier="B", conf="Verified",
         summary="QoL+性能：相机静止跳帧/暂停冻结弹道/屏蔽分析/高帧率模拟平滑/开发者模式；Feature<T> 开关框架",
         primary=["Utility", "World"],
         secondary=["UI", "Mod Lifecycle"],
         techniques=["Harmony Prefix", "Config callback hot-toggle"],
         harmony=True, ui=False, assets=False, persistence=False, evidence=5,
         wb=["Config", "MapBox.calculateCurElapsed", "ZoneCamera.update", "Projectile.update", "MapStats.recalcCounters"],
         nml=["BasicMod<T>/GetConfig (Verified)", "default_config.json Callback (Verified)"],
         patterns=[("feature-toggle-framework", "Feature<T> 组件+配置回调热切换补丁"),
                   ("frame-rate-adaptive-sim", "按帧率缩放模拟步长")]),
    dict(id="ref:incensefiredway", name="IncensefiredWay", tier="B", conf="Mostly Verified",
         summary="神道内容：6 岁随机神性天赋，香火值 93 级阶梯升级（属性/攻击/转化信徒/传送/召唤），FMOD 直放音频",
         primary=["Traits", "Actor"],
         secondary=["Combat", "Assets", "UI", "Save/Persistence", "Kingdom"],
         techniques=["Harmony Prefix", "Harmony Postfix", "Asset registration", "Custom data", "UI injection"],
         harmony=True, ui=True, assets=True, persistence=True, evidence=6,
         wb=["ActorTrait", "BaseStatAsset", "ProjectileAsset", "AssetManager", "Actor.updateAge", "World.world.projectiles"],
         nml=["BasicMod<T>/ModConfig (Verified)", "Hotfixable (Verified)"],
         patterns=[("actor-data-custom-stat", "actor.data 自定义浮点属性三件套"),
                   ("trait-upgrade-chain", "action_special_effect 阶梯+upTrait 升级链"),
                   ("immunity-prefix-veto-suite", "Prefix 批量否决负面状态=霸体")]),
    dict(id="ref:familytree", name="FamilyTree", tier="B", conf="Verified",
         summary="单位窗口族谱按钮：全屏平移缩放思维导图（含死者+死因），countDeath 快照补全死者亲属关系",
         primary=["UI"],
         secondary=["Actor", "Events", "Kingdom", "Clan"],
         techniques=["Harmony Prefix", "Harmony Postfix", "UI injection", "UGUI overlay"],
         harmony=True, ui=True, assets=False, persistence=False, evidence=5,
         wb=["Actor.countDeath", "Actor.getParents/getChildren", "UnitWindow.OnEnable", "ScrollWindow", "World.world.units"],
         nml=["BasicMod (Verified)", "AutoLayoutWindow<T> (Verified)"],
         patterns=[("death-snapshot-recorder", "countDeath Postfix 死亡快照"),
                   ("ugui-pan-zoom-overlay", "纯 UGUI 平移缩放关系图")]),
    dict(id="ref:buzzoff", name="BuzzOff", tier="B", conf="Verified",
         summary="阻止昆虫单位进化 + 蜂巢生成否决与定时清扫；'Prefix 置空 __result' 否决范式微型样本",
         primary=["Buildings", "Actor"],
         secondary=["Utility"],
         techniques=["Harmony Prefix", "Coroutine polling"],
         harmony=True, ui=False, assets=False, persistence=False, evidence=4,
         wb=["BuildingManager.addBuilding", "ActionLibrary.tryToEvolveUnitViaMonolith", "World.world.buildings"],
         nml=["BasicMod<T>/GetConfig (Verified)"],
         patterns=[("spawn-veto-prefix", "Prefix 置空 __result 否决生成")]),
    dict(id="ref:mapdeal", name="MapDeal", tier="B", conf="Verified",
         summary="IMGUI 地图工具：tile 快照→镜像/列阵/四角/缩放盖章回地图+去噪+自定义 Zone 重建；零 Harmony 纯反射",
         primary=["Map"],
         secondary=["World", "UI", "Assets"],
         techniques=["Reflection", "Public API only", "OnGUI", "Generation chain replay"],
         harmony=False, ui=True, assets=False, persistence=False, evidence=5,
         wb=["MapBox.tiles_map", "MapAction.terrafoamTile", "SmoothLoader", "MapSizeLibrary", "WorldTile.neighboursAll"],
         nml=["(none - NCMS legacy)"],
         patterns=[("map-snapshot-stamp", "地图快照→印章变换"),
                   ("smoothloader-generation-chain", "复刻世界生成任务链")]),
    dict(id="ref:creepmobboost", name="CreepMobBoost", tier="B", conf="Verified",
         summary="天灾衍生生物 AI 主动筑巢：运行时注入 BehaviourTaskActor+DecisionAsset 到现有种族，零 Harmony",
         primary=["Actor", "Buildings"],
         secondary=["AI", "Assets", "Mod Lifecycle"],
         techniques=["Runtime asset injection", "BehaviourActionActor inheritance", "Config"],
         harmony=False, ui=False, assets=True, persistence=False, evidence=4,
         wb=["AssetManager.tasks_actor", "AssetManager.decisions_library", "Toolbox.checkArraySize", "World.world.buildings.addBuilding"],
         nml=["BasicMod<T>/GetConfig (Verified)"],
         patterns=[("runtime-decision-injection", "运行时 decision+task 注入"),
                   ("building-asset-rebalance-config", "建筑数值配置化修改")]),
    dict(id="ref:worldresilience", name="WorldResilience", tier="B", conf="Verified",
         summary="侵蚀反向化：岩石风化成土/荒地复绿——世界自愈；自定义 world_regrow 法则；NML 旧式 IMod 接口",
         primary=["Map", "World"],
         secondary=["Assets", "Utility"],
         techniques=["Harmony Prefix(replace)", "Traverse private access", "Custom asset"],
         harmony=True, ui=False, assets=True, persistence=False, evidence=4,
         wb=["WorldBehaviourActionErosion.updateErosion", "WorldLaws.init", "PlayerOptionData", "MapAction.terraformMain", "IslandsCalculator"],
         nml=["IMod OnLoad/OnUnload (Verified-legacy)"],
         patterns=[("reverse-erosion-regrow", "逆向侵蚀自愈"),
                   ("custom-world-law-option", "WorldLaws.init Postfix 注册法则"),
                   ("traverse-private-map-api", "Traverse 访问地图私有 API")]),
    dict(id="ref:nerffiredamage", name="NerfFireDamage", tier="C", conf="Verified",
         summary="Prefix 全量替换 burningEffect：烧血 10%→1%；教科书级状态效果替换微型样本",
         primary=["Combat"], secondary=["Utility"],
         techniques=["Harmony Prefix(replace)"],
         harmony=True, ui=False, assets=False, persistence=False, evidence=2,
         wb=["StatusLibrary.burningEffect", "BaseSimObject.getMaxHealthPercent"],
         nml=["BasicMod<T>/LogInfo (Verified)"],
         patterns=[("status-effect-replace-prefix", "状态效果全量替换")]),
    dict(id="ref:unlock-all", name="Unlock all", tier="C", conf="Verified",
         summary="NCMS 遗留：开诅咒世界法则+献祭计数 500 全解锁",
         primary=["World"], secondary=[],
         techniques=["Direct asset field flip", "Manual Harmony postfix"],
         harmony=True, ui=False, assets=False, persistence=False, evidence=2,
         wb=["WorldLawAsset.default_state", "CursedSacrifice.reset"],
         nml=["(none - NCMS)"],
         patterns=[("world-law-default-flip", "world_law default_state 翻转")]),
    dict(id="ref:hanhai-unlock-all", name="寒海的全解锁", tier="C", conf="Verified",
         summary="NCMS 遗留：首帧+组合键调用 GameProgress 官方解锁后门",
         primary=["Utility"], secondary=[],
         techniques=["Update polling", "First-frame gate"],
         harmony=False, ui=False, assets=False, persistence=False, evidence=2,
         wb=["GameProgress.unlockAllAchievements", "GameProgress.debugUnlockAll"],
         nml=["(none - NCMS)"],
         patterns=[("gameprogress-debug-unlock", "官方 debug 解锁入口")]),
    dict(id="ref:simple-chinese-localization", name="简单汉化", tier="C", conf="Verified",
         summary="NML 本地化管线参考实现：IReloadable 热重载 + LocalizedText.Start Postfix 修刷新",
         primary=["Localization"], secondary=["UI"],
         techniques=["Harmony Postfix", "IReloadable hot reload", "LM.LoadLocale"],
         harmony=True, ui=False, assets=False, persistence=False, evidence=2,
         wb=["LocalizedText.Start", "LocalizedTextManager", "PossessionUI"],
         nml=["BasicMod/IReloadable (Verified)", "LM.LoadLocale/ApplyLocale (Verified)"],
         patterns=[("locale-hot-reload", "热重载语言文件"),
                   ("localizedtext-refresh-postfix", "切语言不刷新修复点")]),
]


def main() -> None:
    catalog = []
    matrix_rows = []
    pattern_rows = []
    for mod in MODS:
        mod_id = mod["id"].replace("ref:", "")
        catalog.append({
            "source_id": mod["id"],
            "name": mod["name"],
            "tier": mod["tier"],
            "summary": mod["summary"],
            "primary_systems": mod["primary"],
            "secondary_systems": mod["secondary"],
            "techniques": mod["techniques"],
            "worldbox_api_areas": mod["wb"],
            "nml_api_areas": mod["nml"],
            "harmony": mod["harmony"],
            "ui": mod["ui"],
            "assets": mod["assets"],
            "persistence": mod["persistence"],
            "key_files": [f"mods/{mod_id}.md"],
            "pattern_candidates": [p[0] for p in mod["patterns"]],
            "confidence": mod["conf"],
            "profile": f"mods/{mod_id}.md",
        })
        for system in mod["primary"]:
            matrix_rows.append([mod["id"], system, "primary", mod["evidence"], mod["conf"]])
        for system in mod["secondary"]:
            matrix_rows.append([mod["id"], system, "secondary", 1, mod["conf"]])
        for pid, goal in mod["patterns"]:
            pattern_rows.append({
                "pattern_id": f"candidate:{pid}",
                "goal": goal,
                "system": (mod["primary"] or ["Utility"])[0],
                "mod_id": mod["id"],
                "file": f"mods/{mod_id}.md",
                "symbol": "",
                "reason": mod["summary"][:80],
                "confidence": "verified" if mod["conf"] == "Verified" else "inferred",
            })

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "catalog.json").write_text(
        json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    with open(OUT / "catalog.csv", "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["mod_id", "name", "tier", "harmony", "ui", "assets", "persistence",
                         "primary_systems", "confidence", "profile"])
        for mod in catalog:
            writer.writerow([mod["source_id"], mod["name"], mod["tier"], mod["harmony"], mod["ui"],
                             mod["assets"], mod["persistence"], "|".join(mod["primary_systems"]),
                             mod["confidence"], mod["profile"]])
    with open(OUT / "system-matrix.csv", "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["mod_id", "system", "role", "evidence_count", "confidence"])
        writer.writerows(sorted(matrix_rows))
    with open(OUT / "pattern-candidates.jsonl", "w", encoding="utf-8") as f:
        for row in pattern_rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
    print(f"catalog: {len(catalog)} mods, matrix: {len(matrix_rows)} rows, patterns: {len(pattern_rows)}")


if __name__ == "__main__":
    main()
